### ISSUE TITLE
Re-enable tests for Chocolatey LaTeXML package

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-latexml#4]
Regarding:
https://github.com/metanorma/chocolatey-latexml/blob/23648bcbdaac92bcd440bc206ae64080bce6e638/tools/chocolateyinstall.ps1#L8

From @brucemiller 

> It'd be a shame to disable tests, since that catches installation problems earlier rather than later.
> Which tests produce this message?

@CAMOBAP795 could you help answer @brucemiller ? Thanks!

**Comment by CAMOBAP** [comment]
@brucemiller I 100% agree with you, and I hate this solution

But tests fails when user with Administrator rights install package I noted about this in comment https://github.com/metanorma/chocolatey-latexml/blob/master/tools/chocolateyinstall.ps1#L4-L7

From other side because we removed `miktex` dependency maybe it will works now 

I have created `enable-test` branch, anyway thanks for note this

**Comment by ronaldtse** [comment]
@CAMOBAP795 @brucemiller actually wants to improve the tests at LaTeXML so that the test will still pass regardless of whether `kpsewhich` is installed.

Could you let him know the full output so his team knows where to address this? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse I cannot find old ones on appveyor but soon https://ci.appveyor.com/project/ribose/chocolatey-latexml/builds/23003734 will be started

**Comment by CAMOBAP** [comment]
@CAMOBAP795 @brucemiller it works now!

**Comment by CAMOBAP** [comment]
@CAMOBAP795 @brucemiller merged

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !
